### ISSUE TITLE
[BUG] Context Menu options not working in Firefox

### ISSUE THREAD

**Issue by SakuraRhymes** [tfedor/AugmentedSteam#1125]
The Context Menu options (eg "Search Steam Store for '...' ) fails to toggle / cannot be enabled.
Below is the console error log:
```
Error: Type error for parameter permissions (Error processing permissions.0: Value "contextMenus" must either: must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], or be one of ["webNavigation"]) for permissions.request.
    request Permissions.js:47
    requestOption Permissions.js:83
    f options.js:219
    S options.js:256
```

Augmented Steam Version: 2.0.1
Browser Version : Firefox 86.0.1 (64-bit)

**Comment by candela97** [comment]
FF doesn't support `contextMenus` as an optional permission: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions#browser_compatibility, and it's already listed in `permissions` anyway, so we shouldn't need to request it again.

@MxtOUT Can it be moved to required permissions for all platforms? Will the Chrome people complain? Otherwise it seems like we'll need to implement browser detection...
