### ISSUE TITLE
[BUG] Inconsistent Customize Button

### ISSUE THREAD

**Issue by Revadike** [tfedor/AugmentedSteam#1149]
![image](https://user-images.githubusercontent.com/4411977/118060080-48a06380-b392-11eb-8d18-896b4aa0f3a9.png)

The label "Customize" looks out of place because it's not CAPITALIZED. I suggest you turn this label into uppercase to make it look more consistent.
Maybe even add a counter to display how many sections you've selected to show/hide.

**Comment by candela97** [comment]
Oops I never noticed this when testing since my store is in Chinese.

As for the counter I think it's better to put it in the popup, otherwise the button will become larger (and more distracting) than it already is and I recall there have been requests to add the option to hide it. I'm not sure if this is needed though, there're not many options and what's selected is visible at a glance.
