### ISSUE TITLE
[BUG] Customize function will not work when visiting Steam homepage with URL query string.

### ISSUE THREAD

**Issue by B5F** [tfedor/AugmentedSteam#1152]
### Expected Behavior
Customize button would show up and all of its functions work.

### Actual Behavior
Customize button does not show up.
And customized settings, like hiding sections or default homepage tab would not work.

### Steps to Reproduce the Problem

  1. Visit Steam homepage with URL query string. For example, [https://store.steampowered.com/?l=english](https://store.steampowered.com/?l=english)

### Specifications

  - Augmented Steam Version: 2.0.1
  - Browser Version : Firefox 88.0.1

**Comment by candela97** [comment]
yeah our url match pattern for the homepage specific script doesn't match query strings, so only default features are loaded. Should probably add `"*://store.steampowered.com/?*"`

**Comment by Revadike** [comment]
> yeah our url match pattern for the homepage specific script doesn't match query strings, so only default features are loaded. Should probably add `"*://store.steampowered.com/?*"`

Wouldn't that match all store pages?
There is a regex to avoid that, but I think it's better to parse the URL and evaluate host, path and query components separately.

**Comment by candela97** [comment]
> Wouldn't that match all store pages?

I don't think so...
But maybe we need to update all match patterns to match query strings, I think nearly all Steam pages allow using `?l=` to specify the language.

**Comment by Revadike** [comment]
or maybe parse the URL's for finer control/checking.

**Comment by MxtOUT** [comment]
> Wouldn't that match all store pages?

No, the `?` is just a literal, it doesn't mean "zero or one".

> But maybe we need to update all match patterns to match query strings, I think nearly all Steam pages allow using ?l= to specify the language.

This should be covered with the `ManifestTransformerPlugin.cjs`.
For every match that doesn't end with `*` or `/` it adds the same match but with query string support.
It didn't get added in this case because the match had a trailing slash.
But this trailing slash was necessary, since a host name needs to be finished with a slash

![image](https://user-images.githubusercontent.com/14999077/121801627-836b1500-cc38-11eb-981f-e5dac990851f.png)
