### ISSUE TITLE
[BUG] Steam store page's extra links are not displayed

### ISSUE THREAD

**Issue by jfjx** [tfedor/AugmentedSteam#1175]
### Expected Behavior
The link buttons to SteamDB, PCGamingWiki, etc are displayed on an individual app page around the right side: 
"Popular user-defined tags for this product: Tags

View Your Queue   

// Extra links list HERE //

Is this game relevant to you?"

### Actual Behavior
Screenshot: 
![image](https://user-images.githubusercontent.com/12727188/121440263-88bf2a00-c9c2-11eb-99ec-883b246b07bd.png)

The link buttons are not displayed with this console message: 
 Augmented Steam v2.0.1  https://augmentedsteam.com
app.js:1 V
app.js:1 Error while applying feature V
(anonymous) @ app.js:1
app.js:1 DOMException: Failed to execute 'insertAdjacentElement' on 'Element': The new child element contains the parent.
    at V._moveExtraLinks (chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js:1:67738)
    at V.apply (chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js:1:65229)
    at chrome-extension://dnhpnfgdlenaccegplpojghhmaamnnfp/js/store/app.js:1:136695
(anonymous) @ app.js:1

### Steps to Reproduce the Problem

  1. Open any individual app's Steam store page on Google Chrome
  2. Check the corner where extra links were used to be

### Specifications

  - Augmented Steam Version: v2.0.1
  - Browser Version : Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by Christsnatcher** [comment]
Just to confirm, I'm having the very same issues both in latest Chrome and FireFox using Augmented Steam v2.0.1.

**Comment by Revadike** [comment]
Can someone pin this issue maybe?

**Comment by MxtOUT** [comment]
Done

**Comment by Black3ird** [comment]
Just to keep it alive;

### Actual Behavior
Now it shows nothing in the same area even if tried it on latest Chrome and latest Firefox on empty Profiles so to eliminate all interference from settings and extensions but only Augmented Steam installed. Rest of all the functions from Augmented Steam works, but the sidebar linkings had disappeared. I even tried to change DNS or Network or even VPN to eliminate further suspicion.

### Plausible Theory
Valve "changed" something in their Steam Store pages like an anchor that Augmented Steam was using to "inject" their code into Steam Page but now that anchor being changed to something else, this function becomes defunct as there's nothing to anchor to so there's nothing shown. I can't be sure of this but I've been an advanced uBlock user and knowing intermediate CSS to "inject" or find my anchors (selector or whatever they're called) in HTML pages so that making an educated guess here.


### Temporary Solution
Thanks to many Userscripts like on https://greasyfork.org/en/scripts/26273-steam-web-integration and via Chrome Context Menu Search extension I was able to somewhat restore of broken Augmented Steam functionality to some degree for those missing 18 linkings to 3rd party sites but this isn't a robust solution like Augmented was in few weeks prior to this "Bug".

### Asking Confirmation
If this "works" for anyone please Comment here with a Screenshot if possible so that we may know it's either _some_ of us affected by it or **all** of us are suffering this bug. This will help tremendously to eliminate some of the many possible sources of the bug.

**Comment by shigutso** [comment]
@Black3ird the issue was already fixed in the code, but they need to release a new version with this and other fixes so your browser updates to the new version. Latest version is 2.0.1 from March 9th, and the bug was fixed June 10th https://github.com/tfedor/AugmentedSteam/pull/1176

You can build the extension manually with the latest code following the Building instructions:
https://github.com/tfedor/AugmentedSteam#building-extension
