### ISSUE TITLE
[FEATURE REQUEST] Hide owned games on store page

### ISSUE THREAD

**Issue by lingsamuel** [tfedor/AugmentedSteam#1220]
### Current Behavior (if any)
Owned games can now be highlighted, but still show up on the store page.

### Desired Behavior
Add option to hide owned games.

### Motivation / Use Case for Changing the Behavior
In most cases, users can't do anything with owned games except buy DLC.
Showing owned games on the store page only distracts the user (especially for those who, like me, own hundreds of games).

**Comment by kirara** [comment]
If I read this right, there's an option to "Hide items in my library" which does exactly that.

**Comment by candela97** [comment]
On search pages there's a native option to hide games already in your library, I find this the most useful. For the storefront, tag/genre pages and other sections we could have owned items blurred out like Steam does for ignored items, but outright hiding them may not be the best idea due to possible visual glitches caused by the missing elements.

**Comment by lingsamuel** [comment]
Visual glitches may be a problem, but it would be great if users could choose to accept it or not.
For me, having ~1k games, already owns most of games in the store page. It's annoying to see them again and again.

**Comment by lingsamuel** [comment]
Or instead of highlighting/dimming them, we cloud set the opacity to 0%.

**Comment by candela97** [comment]
If you insist, you can also use a content blocker like uBlock Origin to achieve this, which is much better equipped to handle hiding unwanted content. A custom filter like `store.steampowered.com##.ds_owned` should cover most cases.
