### ISSUE TITLE
[BUG] No [+] button for user-defined tags when slider is expanded

### ISSUE THREAD

**Issue by Biiox** [tfedor/AugmentedSteam#1253]
When the media slider (unsure what to call it, but the button says slider) is expanded ![image](https://user-images.githubusercontent.com/40674515/131803636-d51734bc-e464-49f0-afeb-108efd52d042.png)
The game description panel moves down and the ![image](https://user-images.githubusercontent.com/40674515/131803500-ece9e318-c18d-4565-9723-6ba232744c48.png) view and edit tags button disappears.

Pictures are from Firefox but this happens on Chrome as well.

![image](https://user-images.githubusercontent.com/40674515/131805486-852d9c42-4be3-40e4-a320-0b80b5ade411.png)

### Expected Behavior
![firefox 02 09 2021_10-10-33](https://user-images.githubusercontent.com/40674515/131803994-05638a85-cc8a-45c1-925d-23f27b8bbb6c.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/40674515/131804202-c210c068-5fcb-4bc9-b985-7aefd22b1e0e.png)

### Specifications

  - Augmented Steam Version:  **2.1.0**
  - Browser Version : **Firefox 91.0.2 (64-bit)** & **Chrome 93.0.4577.63 (Official Build) (64-bit)**

**Comment by candela97** [comment]
Yeah it was like this since this feature landed in ES. The button has been removed purposely with a comment stating "issues with having duplicates of these on page when trying to add tags", though I tested a bit and didn't notice any immediate issues. I'll test some more but I think it can probably be restored.
