### ISSUE TITLE
Quick/Instant Sell button gives 400: Bad Request

### ISSUE THREAD

**Issue by headman78** [tfedor/AugmentedSteam#142]
Clicking Quick or Instant Sell button gives this error: One or more requests failed:
https://steamcommunity.com/market/sellitem/(400: Bad Request)

Using Firefox 66.0b13.

**Comment by MxtOUT** [comment]
Does that happen for every item?

**Comment by headman78** [comment]
Yes, I have 10 trading cards that I tried.

**Comment by MxtOUT** [comment]
Does the dev console only print this or is there more?

**Comment by headman78** [comment]
Only that.

**Comment by KarlCastle** [comment]
The quoted error message is from `ProgressBar`. When an XHR fails in Firefox from an extension context, it doesn't log to the console.

This seems to be the same bug behind jshackles/Enhanced_Steam#1494 because in the refactor we reverted the patch I wrote to fix it.  When I copy/pasted the old patch into Augmented Steam and updated the variable names (event => e) it worked for me to list two cards on FF56 and FF65.

**Comment by Fooughhy** [comment]
Is there any progress on this bug? Have had this for a long time now.

FF 67.0.1

**Comment by MxtOUT** [comment]
@KarlCastle Could you create a PR for this?

**Comment by MxtOUT** [comment]
Fixed with #312
