### ISSUE TITLE
[fifefox]Augmented Steam don't work on fifefox

### ISSUE THREAD

**Issue by Abelishe** [tfedor/AugmentedSteam#145]
Hello,
I would like help, the extension is not working in firefox browser(65.0.2-64x)
what can I do?
![steam](https://user-images.githubusercontent.com/48338655/54000111-eb128b80-4124-11e9-8a86-bad6b9ce6241.JPG)
![steam02](https://user-images.githubusercontent.com/48338655/54000112-ebab2200-4124-11e9-852b-bb7f06bc4d55.JPG)

**Comment by tfedor** [comment]
Can you see anything in browser console?

**Comment by dsyo2008** [comment]
```
[Violentmonkey][page][CleanHide & Enable RightClick-Copy] 
ReferenceError: GM_registerMenuCommand is not defined
GM_registerMenuCommand is not defined store.steampowered.com:1:15404
    h https://store.steampowered.com/:1
    j https://store.steampowered.com/:1
    j https://store.steampowered.com/:1
    value https://store.steampowered.com/:1
    <anonymous> https://store.steampowered.com/ line 1 > scriptElement:1
    <anonymous> https://store.steampowered.com/ line 1 > scriptElement:1
    i https://store.steampowered.com/:1
    i https://store.steampowered.com/:1
    j https://store.steampowered.com/:1
    O https://store.steampowered.com/:1
    load https://store.steampowered.com/:1
'DEFAULT' policy is picked instead of 'DEFAULT' content_script.js:750:25
(2) […]
​
0: "CatPW_Manage"
​
1: "CatPW"
​
length: 2
​
<prototype>: Array []
 
Object { StorageSave: true, UpdataConfig: {…}, StorageExp: 365 }
 undefined undefined undefined line 1 > scriptElement:881:19
unreachable code after return statement[详细了解] gwdang-notifier-ff.js:34511:3

```
Same problem

**Comment by MxtOUT** [comment]
Do you guys have [GreaseMonkey ](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)installed?

**Comment by dsyo2008** [comment]
> 
> 
> Do you guys have [GreaseMonkey ](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/)installed?

No, why do you want to install this? What is the relationship with this extension?

**Comment by MxtOUT** [comment]
Because the error you pasted in here references Grease Monkey/Violentmonkey.
Have you tried disabling Violentmonkey?

**Comment by MxtOUT** [comment]
@Abelishe Do you have the same error message?

**Comment by dsyo2008** [comment]
> 
> 
> Because the error you pasted in here references Grease Monkey/Violentmonkey.
> Have you tried disabling Violentmonkey?

Sorry, it turns out that I am operating incorrectly, the real log is here.
`Error: Could not establish connection. Receiving end does not exist. background.js:1:417
Object { type: "evt_getconf" }
background.js:3915:2
Error: Could not establish connection. Receiving end does not exist. background.js:1:417
即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://steamstore-a.akamaihd.net/public/shared/javascript/flot-0.8/jquery.flot.js?v=.zrJjtPpGflQQ”的脚本。[详细了解] DYNASTY_WARRIORS_8_Xtreme_Legends_Complete_Edition___with
即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://steamstore-a.akamaihd.net/public/shared/javascript/flot-0.8/jquery.flot.resize.js?v=.TWn5-WgQL6_C”的脚本。[详细了解] DYNASTY_WARRIORS_8_Xtreme_Legends_Complete_Edition___with
即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://steamstore-a.akamaihd.net/public/shared/javascript/flot-0.8/jquery.flot.selection.js?v=.EGbodhwqG-oT”的脚本。[详细了解] DYNASTY_WARRIORS_8_Xtreme_Legends_Complete_Edition___with
即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://steamstore-a.akamaihd.net/public/shared/javascript/flot-0.8/jquery.flot.time.js?v=.wh3SCHrBBvNi”的脚本。[详细了解] DYNASTY_WARRIORS_8_Xtreme_Legends_Complete_Edition___with
[Violentmonkey][page][CleanHide & Enable RightClick-Copy] 
ReferenceError: GM_registerMenuCommand is not defined
GM_registerMenuCommand is not defined DYNASTY_WARRIORS_8_Xtreme_Legends_Complete_Edition___with:1:15404
'DEFAULT' policy is picked instead of 'DEFAULT' content_script.js:750:25
<unavailable> <unavailable> undefined undefined undefined line 1 > scriptElement:881:19
uncaught exception: 0
[SteamDB] Matched currency as "CNY" common.js:76:2
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no]
unreachable code after return statement gwdang-notifier-ff.js:34511:3
指向“https://browser.gwdang.com/extension?ac=serverCheck&from_device=firefox&protocol=https:&callback=jQuery1113080324850056672_1552061007157&format=jsonp&union=union_gwdang&version=1540628977362&from_device=firefox&crc64=1&_=1552061007158”的 <script> 加载失败。 DYNASTY_WARRIORS_8_Xtreme_Legends_Complete_Edition___with:1:1
Content Security Policy: 页面设置阻止读取位于 https://browser.gwdang.com/extension?ac=serverCheck&from_device=firefox&protocol=https:&callback=jQuery1113080324850056672_1552061007157&format=jsonp&union=union_gwdang&version=1540628977362&from_device=firefox&crc64=1&_=1552061007158 的一项资源("script-src")。
undefined is not a valid URL. background.js:343
Sending message that cannot be cloned. Are you trying to send an XPCOM object? MessageChannel.jsm:968:8
[SteamDB] GetCurrentPlayers failed to load common.js:76:2
TypeError: gFindBar is undefined[详细了解] ButtonEventListener.uc.js:97:7
Sending message that cannot be cloned. Are you trying to send an XPCOM object? MessageChannel.jsm:968:8
[SteamDB] GetPrice failed to load common.js:76:2
XML 解析错误：格式不佳
位置：https://api2.poperblocker.com/view/update
行 1，列 1： update:1:1
TypeError: gFindBar is undefined[详细了解] ButtonEventListener.uc.js:97:7
`

**Comment by MxtOUT** [comment]
That seems to me like you're using a lot of extensions.
Could you name all of them (including the user scripts from ViolentMonkey) and try to disable everything to check if it works then?

**Comment by dsyo2008** [comment]
> 
> 
> That seems to me like you're using a lot of extensions.
> Could you name all of them (including the user scripts from ViolentMonkey) and try to disable everything to check if it works then?
Tried, disabled or the same

**Comment by rainyAugust** [comment]
When setting the language of steam to Chinese, augmented steam does not work.
When set to English, everything works fine.

**Comment by MxtOUT** [comment]
@rainyAugust I can't reproduce this, do you get any error messages in the Dev Console (F12)?

**Comment by rainyAugust** [comment]
No error,as you see
Chinese

English

发送自 Windows 10 版邮件应用

发件人: MxtOUT
发送时间: 2019年3月9日 19:56
收件人: tfedor/AugmentedSteam
抄送: rainyAugust; Mention
主题: Re: [tfedor/AugmentedSteam] [fifefox]Augmented Steam don't work onfifefox (#145)

@rainyAugust I can't reproduce this, do you get any error messages in the Dev Console (F12)?

**Comment by rainyAugust** [comment]
no error, as you see


> 
> 
> @rainyAugust I can't reproduce this, do you get any error messages in the Dev Console (F12)?

no error, as you see
Chinese
![Chinese](https://user-images.githubusercontent.com/48341144/54071811-ee388380-42ac-11e9-92eb-2f054b3c560a.png)
English
![English](https://user-images.githubusercontent.com/48341144/54071815-fa244580-42ac-11e9-9cb7-03c0a718c587.png)

**Comment by Killogy** [comment]
I tested and @rainyAugust is right, augmented Steam, doesn´t work when setting Steam language to Simplified Chinese or Spanish - Spain.

It Works when I set Spanish - Latin america language, this language bug is the culprit why augmented latest version 0.9.3 or 0.9.4 stopped working on Firefox 56.0.2 #26.

So if I set Steam language to Spanish - Spain, augmented addon doesn´t works but if I change language to Spanish Latin america it works.

**Comment by KarlCastle** [comment]
I can't replicate this on FF56 or FF65, in any of the languages I tried :(

> P.S: While testing, I Think found another bug, I´m running Firefox 56.0.2 vanilla version, I have set Firefox Histoy setting at "Use Custom settings for history" and unchecked "Accept cookies from sites", then Augmented doesn´t work on Community pages and profile pages, store is working.

If you find a new issue, please report it as a new issue.

Firefox treats "Accept cookies from sites" as a catch all for "Let this site store data on this PC", and when the setting is turned off, any extension that uses cookies, `localStorage` or `IndexedDB` will start behaving erratically. For me, Augmented Steam won't load in the store without cookies. (And I can't login to Steam, &c..)

**Comment by Killogy** [comment]
> If you find a new issue, please report it as a new issue.
> 
> Firefox treats "Accept cookies from sites" as a catch all for "Let this site store data on this PC", and when the setting is turned off, any extension that uses cookies, `localStorage` or `IndexedDB` will start behaving erratically. For me, Augmented Steam won't load in the store without cookies. (And I can't login to Steam, &c..)

I opened a new issue reporting this.

Enhanced Steam extension is working even with Firefox cookies disabled. Augmented 0.9.3 is working on the Steam Store with cookies disabled. Obviously, if you want to login to Steam you must add to the exclusion list https://store.steampowered.com/ and https://steamcommunity.com and maybe another subdomains.

Augmented 0.9.5 is not working if I set Simplified Chinese or Spanish - Spain, and also if I set cookies disabled. With Augmented 0.9.3 you do not need stay logged to the Steam to load Augmented features on Steam Sore and Steam profiles, but latest 0.9.5 stopped working If Firefox are disabled.

So If I want to use Augmented 0.9.5 I need set Steam language to Spanish - Latin america and now I must enable cookies. I´m running Firefox with cookies disabled and specified sites added to the exclusion sites to accept its cookies.

**Comment by LukasThyWalls** [comment]
With two different computers (32 bits & 64 bits).
Both with lastest Firefox (65.0.2).
Both with lastest Augmented Steam (0.9.5) installed.
Both with cookies set to "Strict" (i put "Standart" and "Custom" settings, but didn't make any difference to me).

I have Steam in Spanish (Spain), and Augmented Steam do nothing. Don't load, it's like it's not installed, doesn't appear the Augmented Steam loading bar/dot.
But if i change the language to English, Augmented Steam works, it seems all fine. If i put back it to Spanish (Spain), is gone again.

I didn't change anything, i only upgrade Firefox and Augmented Steam to the new versions (when pop out).

**Comment by Ryuzaki-MrL** [comment]
It's also not working in portuguese, only in english for me. It was before, but after an update around the end of february it broke.

**Comment by Killogy** [comment]
> With two different computers (32 bits & 64 bits).
> Both with lastest Firefox (65.0.2).
> Both with lastest Augmented Steam (0.9.5) installed.
> Both with cookies set to "Strict" (i put "Standart" and "Custom" settings, but didn't make any difference to me).

I´m running Firefox 56.0.2 64 bits and the problem about cookies issue is happening only under Firefox 56.0.2 and Augmented 0.9.5 (Augmented 0.9.3 is working properly) #169 . With latest Firefox versions augmented is working properly, regardless of the cookie settings. The only issue using latest firefox version and Augmented 0.9.5 is about the language bug, some Steam languages disables Augmented 0.9.5

**Comment by MxtOUT** [comment]
So, about the language problem: Tested this with 0.9.5 and could reproduce it this time on Waterfox 56.2.8 (64-bit).
Then I tested it again on the current [develop](https://github.com/tfedor/AugmentedSteam/tree/develop) and it works, but I don't know what changed that tbh

**Comment by MxtOUT** [comment]
Working now?

**Comment by rainyAugust** [comment]
Yes




------------------ 原始邮件 ------------------
发件人: "MxtOUT"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 晚上10:42
收件人: "tfedor/AugmentedSteam"<AugmentedSteam@noreply.github.com>;
抄送: "Just4Fun"<leon.f@foxmail.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [tfedor/AugmentedSteam] [fifefox]Augmented Steam don't work onfifefox (#145)




Working now?
