### ISSUE TITLE
Package info buttons

### ISSUE THREAD

**Issue by MonolithOrchids** [tfedor/AugmentedSteam#199]
Games with more than one package has a bug that will show all package info links stacked at first one.

Black Desert Online and Tom Clancy's Rainbow Six Siege are good examples.

Cheers!
![dL8Em](https://user-images.githubusercontent.com/30219468/54651785-1f763800-4a93-11e9-83ae-0e679ff4229d.jpeg)

**Comment by MxtOUT** [comment]
I don't see the "Package info" button at all, what versions of AS and your browser are you using?

**Comment by MonolithOrchids** [comment]
Uh...that's probably a feature from another extension, sorry,

**Comment by Californ1a** [comment]
This should be reopened, it is an issue with AS. The option to enable showing the Package Info buttons is in AS's settings under the Store tab in the General section.

![](https://i.imgur.com/RB6Mqp8.png)

**Comment by Revadike** [comment]
Maybe make a packageid dropdown in case of > 1?

**Comment by Californ1a** [comment]
> Maybe make a packageid dropdown in case of > 1?

It seems to have mostly been fixed now. None of the previous examples have the Package Info buttons going off the edge anymore. However, the main issue is that the Package Info buttons are all in the same line rather than being listed on their respective packages.

For example, with BDO, it has 3 packages, but all 3 of the Package Info buttons are listed on the first one rather than on their own respective packages:
![](https://i.imgur.com/2HPcwPi.png)
The first Package Info button is for the Explorer's Pack, the second one is for the Traveler's Pack, and the third one is for the base game.

Similarly with Hitman 2:
![](https://i.imgur.com/fZdUFYO.png)
The Santa Fortuna Package Info button is displayed correctly, but the Gold Edition Package Info button is alongside the Starter Edition one rather than being on the Gold Edition section.
