### ISSUE TITLE
Broken "Customize" button

### ISSUE THREAD

**Issue by fredfioreze** [tfedor/AugmentedSteam#204]
The "Customize" button in any game store page is broken for me. I still can click and open the menu like in the printscreen, but can't select any option.

Firefox 56.0.2 with Augmented Steam 0.9.5

![321](https://user-images.githubusercontent.com/48899679/54894782-04446780-4e9b-11e9-9510-53571f70bfd6.png)

**Comment by KarlCastle** [comment]
At a glance, this is the same issue as tfedor/AugmentedSteam#164. 0.9.5 isn't installing the CSS styles that hide the menu options and make "Customize" look like a button. This was fixed by #165 for the next release.

I can replicate this on the release version and it's confirmed working correctly in the current `develop` branch.
