### ISSUE TITLE
Early Access banner is misplaced in the Community Hub on Firefox

### ISSUE THREAD

**Issue by KarlCastle** [tfedor/AugmentedSteam#206]
Example, Factorio: https://steamcommunity.com/app/427520

<img src="https://user-images.githubusercontent.com/9707792/55040385-09124280-5078-11e9-825f-00d2116dd4fa.png" width="200" />

Given Steam now has the large scrawl immediately under the app header we could possibly remove the banner from these pages?

**Comment by candela97** [comment]
Happens on Chrome too.

I think it's fine to remove the banner from community pages. I'd even suggest removing this feature because it's somewhat redundant, since the EA tag is already present on store lists, for store pages there's the EA info box, and for search results/curator lists/recommendation pages...etc. there's the popup that will display tags. Changing it into something like "Hide -> Early Access Items in search results and tag pages" will perhaps be more useful.

If the goal is to make it work everywhere, the banner currently doesn't appear on several store lists, for example:
https://store.steampowered.com/software/
https://store.steampowered.com/specials/
https://store.steampowered.com/vr/
https://store.steampowered.com/macos/
https://store.steampowered.com/tags/en/Action/ and other tag pages
https://store.steampowered.com/recommended/ (not logged in) "Also recently viewed" list
https://store.steampowered.com/updated/all/

**Comment by MxtOUT** [comment]
@candela97 That is a separate problem / feature, do you want to open an issue for that?
