### ISSUE TITLE
Option SteamrepCN was removed but SteamrepCN still remains on Chinese players' profiles.

### ISSUE THREAD

**Issue by pirodo** [tfedor/AugmentedSteam#208]
Option SteamrepCN was removed but SteamrepCN still remains on Chinese players' profiles.
Please fix it, thanks!

**Comment by candela97** [comment]
hmm...I'm still not seeing the option to disable steamrepcn links when I set my language to tchinese.

btw the steamrepcn icon is not affected by the "Profile link images" setting (defaults to grayscale).

**Comment by candela97** [comment]
possible cause
https://github.com/tfedor/AugmentedSteam/blob/10554b7af9d092ef0fa436dd6da9c4558ff26ec2/js/options/options.js#L441
should be `if (language !== "schinese" || language !== "tchinese") { `?

**Comment by MxtOUT** [comment]
Good catch, yeah, that always evalutates to `true`

**Comment by candela97** [comment]
After giving it some thought, the original logic is correct afterall. We need it to return `false` if language is `tchinese` or `schinese` in order to not hide the setting.

I can confirm changing this instead works:
https://github.com/tfedor/AugmentedSteam/blob/5c9437581449ef5a0324736b77daf4a5692494ac/js/options/options.js#L440
` let language = SyncedStorage.get("language");`

not sure if it breaks anything though,  I've tested on a fresh install

**Comment by Revadike** [comment]
> I can confirm changing this instead works:

Changing what?
