### ISSUE TITLE
Regional Price Comparison

### ISSUE THREAD

**Issue by RDru** [tfedor/AugmentedSteam#24]
My regional currency (PLN/Poland) is shown with EU flag and there is no EU region in the list. Adding Poland to the list doesn't list it. Changing currency from auto-detect to anything else makes the feature broken - it doesn't show at all. My store language is English.

**Comment by xMikasa** [comment]
View In: feature in Price seems to be only working for USD. Any other currency causes the % section a bit messy.
https://i.imgur.com/qH0ZNu0.png when default is JPY

**Comment by tfedor** [comment]
This should be fixed now, please update and verify for me

**Comment by xMikasa** [comment]
Still a bit bugged i think. But more because I am unsure what exactly the purpose of this feature is. Is USD value just made default for comparison or is our default store price(ie. the value to the right) supposed to be the value for comparison

for example if AUD is our default steam store: https://i.imgur.com/Dq6tYZp.png    

https://i.imgur.com/IwkHG9F.png if USD store isn't one of the values its kinda confusing like this one.

So if the goal of this is to compare prices to USD store always then its working. If the goal however is to compare it to out current store than its not working.

**Comment by RDru** [comment]
Updated. Still bugged as before. I don't see any change.

**Comment by xMikasa** [comment]
Had to change it to automatic than back to another currency for it to take effect. @RDru

**Comment by snakecase** [comment]
I think it fits this issue so I won't open a new one. Kazakhstan's currency doesn't show up in comparison at all. Btw, thank you for continuing ES.

**Comment by tfedor** [comment]
Kazakhstan works correctly for me
![image](https://user-images.githubusercontent.com/5072842/52820655-cf2f4300-30ac-11e9-8bd4-d32bf2be4c6d.png)

**Comment by snakecase** [comment]
@tfedor no luck for me still. Probably because of [this](https://github.com/tfedor/Enhanced_Steam/issues/52#issuecomment-463885822). But again, it shows RUB twice if I add it in settings
![prices](https://user-images.githubusercontent.com/4579891/52831623-1f32f780-30f7-11e9-8318-fb248b30e852.png)
.

**Comment by snakecase** [comment]
Works fine now.
