### ISSUE TITLE
Unable to Full screen videos/trailers

### ISSUE THREAD

**Issue by shatteredhalo** [tfedor/AugmentedSteam#252]
With the Augmented Steam extension enabled, clicking the full-screen button on the Steam media player does nothing. Disabling the extension allows videos/trailers to once again be properly set to full-screen.

Chrome 66.0.3359.181

![aug](https://user-images.githubusercontent.com/50034680/56841577-ab326f80-685c-11e9-977d-2ef7b56cdbef.JPG)

**Comment by KarlCastle** [comment]
Hi, thanks for reporting this.

Unfortunately I can't replicate it on current Chrome (73.0.3683.103 x64), so we'll need more information to try and fix it.

Does the icon react if you hover over it? It should be grey normally and go white when the mouse cursor is over it.

Do you know how to check the browser console for errors? (And if so, are there any? Either before you click on the button, or after?)

Does the HD toggle work?

**Comment by shatteredhalo** [comment]
> Hi, thanks for reporting this.
> 
> Unfortunately I can't replicate it on current Chrome (73.0.3683.103 x64), so we'll need more information to try and fix it.
> 
> Does the icon react if you hover over it? It should be grey normally and go white when the mouse cursor is over it.
> 
> Do you know how to check the browser console for errors? (And if so, are there any? Either before you click on the button, or after?)
> 
> Does the HD toggle work?

It does react. It is grey normally and turns white on mouse cursor hover.

I have attached a screenshot of the browser console readout from a freshly loaded page. Hovering or clicking the full screen button does not create any new entries/errors.

The HD toggle works correctly.

![aug1](https://user-images.githubusercontent.com/50034680/56936076-4593ec80-6ac3-11e9-986b-cf0842287860.JPG)

**Comment by KarlCastle** [comment]
The CORS error is weird. Akamai are absolutely serving it with the correct header, so something has to have stripped it en route. Nothing to do with us though.

I've tried getting a working build of Chrome/Chromium 66 to test with and no dice, just startup crashes :(

The button uses the HTML5 fullScreen API which Chrome has lagged behind in implementing, but none of the features we rely on have changed since Chrome 53.

Does double-clicking on the video toggle fullscreen?

**Comment by shatteredhalo** [comment]
Unfortunately double clicking does not work either.

**Comment by shatteredhalo** [comment]
I should probably add to the double clicking comment: while it does not fullscreen, it does pause/unpause the video.

**Comment by shatteredhalo** [comment]
Also for what it's worth, version 10.0 of Enhanced Steam doesn't have this issue, and full screens properly.

**Comment by KarlCastle** [comment]
My working assumption is that we're relying on something (don't know what exactly) that changed in some (undocumented?) way between Chrome 66 and Chrome 74. Since Google makes older versions of Chrome so hard to obtain we don't officially support anything but the latest version.

It seems like something is going wrong in the event handler but without an error message, and with no ability to replicate the error in a test environment, it makes troubleshooting *exceedingly* difficult.

**Comment by MxtOUT** [comment]
@shatteredhalo Any news on this?

**Comment by shatteredhalo** [comment]
I actually switched back to the closed/deprecated Enhanced Steam over this issue since they way Karl explained it, seeing a fix in Augmented Steam seemed unlikely.

**Comment by shatteredhalo** [comment]
Just an update to confirm that the newest version of Augmented Steam (1.2.1) still has this issue for me.

**Comment by MxtOUT** [comment]
Still not working?
Have you tried it with the latest Chrome?

**Comment by shatteredhalo** [comment]
It does seem to work on newer versions of Chrome. On this machine I have 76.0.3809.100 (Official Build) (64-bit) and the full screen functions as expected.

**Comment by MxtOUT** [comment]
Ok, then I'll close it, since we're only supporting the newest Chrome
