### ISSUE TITLE
Some features aren't working

### ISSUE THREAD

**Issue by bottleblue** [tfedor/AugmentedSteam#26]
Using FF 65 64bit and Win 7 if that matters. These features don't seem to be working:

Highlights don't work in the suggestion popup when typing in the store search box. Highlights and tags don't work in Wishlist. They mostly don't work in store pages. (The game title text gets highlighted if owned but that's about it)

"Show advanced navigation on inventory page"  doesn't work
"Show the number of items on Wishlist" doesn't work
"Set custom background on "Edit Profile" screen" doesn't work
The custom entry under Show Profile Links To doesn't work (still works for Jshackles version)

**Comment by tfedor** [comment]
Advanced navigation should work in v0.9.2 now, number of items on Wishlist should work, as well, but I'm not sure if we're properly respecting setting right now.

**Comment by bottleblue** [comment]
Great keep up the good work!

**Comment by Killogy** [comment]
Also, and running latest addon update and Firefox 56.0.2.

Features under these sections are not working...

Community > Show profile links to
Community > Profile

Only these links are working under Store > Options for information from 3rd-party sites

Show SteamDB links (icon is missing)
Show PCGamingWiki links
Show SteamCardExchange links on store

**Comment by tfedor** [comment]
Hmm, community links are working for me in the last public version already, if they still won't work in 0.9.3 please let me know

**Comment by Killogy** [comment]
It´s not working for me,  I´m running Firefox 56.0.2 and Addon version 0.9.2 latest available on addons.mozilla.org and addon is not activated when browsing My profile and Community

https://i.imgur.com/X5ARlKD.jpg

**Comment by RathaWynter** [comment]
Confirming that Community features are not working in Firefox 55.03 with Augmented Steam 0.9.3.

The fix for Issue #7 seems to have resolved Augmented Steam not working on Store pages, but currently the Augmented Steam options panel at the top of the page does not load on any Community page, nor does any of its functionality work anywhere but on the Store.

**Comment by KarlCastle** [comment]
> (The game title text gets highlighted if owned but that's about it)

Highlighting for Gifts, Guest Passes and Coupons should start working after #80 is merged. (I created #85 when I noticed it wasn't working.)

> Also clicking on "Customize button" under Inventory Show Quick Sale buttons on Steam Community items in inventory , nothing happens

This was separately reported as #86 and will be fixed once #89 is merged.

> Only these links are working under Store > Options for information from 3rd-party sites
> 
> Show SteamDB links (icon is missing)
> Show PCGamingWiki links
> Show SteamCardExchange links on store

I'm seeing:
IsThereAnyDeal
SteamDB (with icon)
PCGamingWiki
OpenCritic
HowLongToBeat
AStats
Metacritic
SteamCardExchange
SteamCharts
SteamSpy

That leaves the WSGF (Widescreen) info that might still be missing?

> `SyntaxError: missing ( before catch community.js:1655:20`

> Community > Show profile links to
> Community > Profile

> Community features are not working in Firefox 55.03 with Augmented Steam 0.9.3

This is fixed by #92. There was a single line of code that needed FF58+ that stopped it working :(

> When I click on **options.js** an about:black window pop up and console show **Error de seguridad: el contenido en moz-nullprincipal:{b0d915ac-4cb4-4e21-b893-7b4b1cac4b7c} no puede cargar datos de moz-extension://87b3d084-5fed-45ae-ae7e-18024018d7cc/js/options.js**

I can't replicate this :( I'm not sure if it relates to the other FF<58 problem?


This issue has become something of a collection of separate issues. I think these are still outstanding:

> Highlights don't work in the suggestion popup when typing in the store search box.

> Highlights and tags don't work in Wishlist.

**Comment by Killogy** [comment]
> > Only these links are working under Store > Options for information from 3rd-party sites
> > Show SteamDB links (icon is missing)
> > Show PCGamingWiki links
> > Show SteamCardExchange links on store
> 
> I'm seeing:
> IsThereAnyDeal
> SteamDB (with icon)
> PCGamingWiki
> OpenCritic
> HowLongToBeat
> AStats
> Metacritic
> SteamCardExchange
> SteamCharts
> SteamSpy
> 
> That leaves the WSGF (Widescreen) info that might still be missing?

These Store > Options for information from 3rd-party sites was not working with previous Augmented version, now are working with latest version 0.9.3.

WSGF (Widescreen) never worked , even with original Enhanced addon.

> > When I click on **options.js** an about:black window pop up and console show **Error de seguridad: el contenido en moz-nullprincipal:{b0d915ac-4cb4-4e21-b893-7b4b1cac4b7c} no puede cargar datos de moz-extension://87b3d084-5fed-45ae-ae7e-18024018d7cc/js/options.js**
> 
> I can't replicate this :( I'm not sure if it relates to the other FF<58 problem?

I click on Customize button, then console prints the line **TypeError: node is null  options.js:391:6** , I click on **options.js:391:6** and Firefox open an about:blank tab and console prints the lines...

**No es posible marcar <input pattern='*'> porque el patrón no es una expresión regular válida: nothing to repeat blank**

My english is not good, but means something like: It is not possible to mark <input pattern='*' because the pattern is not a valid regular expression: nothing to repeat blank** 

and 

**Error de seguridad: el contenido en moz-nullprincipal:{348d371c-9c97-4dd3-99c8-3bde450561eb} no puede cargar datos de moz-extension://87b3d084-5fed-45ae-ae7e-18024018d7cc/js/options.js.**

Security error: content in moz-nullprincipal:{348d371c-9c97-4dd3-99c8-3bde450561eb} can not load data from moz-extension://87b3d084-5fed-45ae-ae7e-18024018d7cc/js/options.js.

**Comment by Killogy** [comment]
Latest version 0.9.4 is not working anymore.

firefox console prints this line, when loading Steam Store or Enable/disable addon.

uncaught exception: 0  (desconocido)

**Comment by tfedor** [comment]
What browser and version?

**Comment by Killogy** [comment]
Firefox 64bits 56.0.2, I uninstalled , and reinstalled previous version and now is not working too. Tested with differents firefox profiles.

**Comment by tfedor** [comment]
Is it vanilla Firefox or something like Waterfox?

**Comment by Killogy** [comment]
vanilla

**Comment by tfedor** [comment]
Hmm, seems like we have broken something for older versions then.

**Comment by Killogy** [comment]
Ok I found something, When installing latest version, and reinstalling previous version, closing firefox and then I need to restore from a firefox profile backup, these files to restore previous addon version funcionality.

addonStartup.json.lz4
storage-sync.sqlite

**Comment by Killogy** [comment]
As I mentioned #145 latest augmented version 0.9.4 and 0.9.5 stopped working on firefox 56.0.2 because the language bug when Steam is set to Simplified Chinese or Spanish - Spain.

It Works when I set Spanish - Latin america language, this language bug is the culprit why augmented 
latest version 0.9.4 or 0.9.5 stopped working on Firefox 56.0.2.

So if I set Steam language to Spanish - Spain, augmented addon doesn´t works but if I change language to Spanish Latin america it works.
