### ISSUE TITLE
[Bug] Displaced profile appearance

### ISSUE THREAD

**Issue by Gudine** [tfedor/AugmentedSteam#349]
Whenever I visit a steam profile (mine or otherwise), the header of the page moves down, disaligning the main page wallpaper with the sides.

![image](https://user-images.githubusercontent.com/29386464/61252133-eb560f80-a732-11e9-9d23-5b3976cb6e25.png)

**Comment by MxtOUT** [comment]
I can't replicate that, are you using FF or Chrome?
When did this bug appear?

**Comment by Gudine** [comment]
I'm using the Chrome extension with Vivaldi, but I also installed Chrome itself to test, and it happens there too, though not in all profiles. After removing and readding the extension in my usual browser, it also stopped happening in all profiles, but it still happens in some.

I don't remember exactly when it started happening, but it was probably early this month.

**Comment by ThisIsABug** [comment]
I can reproduce this in firefox, funny enough the problem is not at the top of the header-box, it is at the bottom: https://github.com/tfedor/AugmentedSteam/blob/develop/js/content/community.js#L724

This forced padding also destroys the layout of profilepages which use an artwork showcase to extend the visibility of their background (like OP used too, look at his artwork showcase, it's not fitting to the background).
Another example (look at the ninjas eyes):
![image](https://user-images.githubusercontent.com/19193534/64075926-f4894480-ccbe-11e9-8557-531b83b52759.png)

**Comment by Revadike** [comment]
Would it be safe to omit this line?

**Comment by ThisIsABug** [comment]
@Revadike I am unsure, for me this "Show SteamRep status on profile pages" adds only the padding, without any "SteamRep-information" (I do not have an account there).

**Comment by MxtOUT** [comment]
I can't reproduce this in Firefox or Chrome on the latest version.
Looking through the code, it shouldn't even add this element if there's no SteamRep data available...

**Comment by ThisIsABug** [comment]
I have to admit I can not reproduce it anymore too. While trying to track it down I lost it.
Some fact which could help in the future if it happens again:
-I could narrow the problem down to one firefox profile (2 running instances on 2 different profiles, only one had the issue, same application-version), which points to the fact that it's not an extension issue alone (if even).
-I think something in the rendering-engine of my firefox broke at the same time (I had rendering issues in the tabbar which vanished at the same time at which I lost the condition).

**Comment by ThisIsABug** [comment]
@Gudine did you ever connect with a remote desktop software to the machine which has this issue?

**Comment by Gudine** [comment]
No...

**Comment by MxtOUT** [comment]
Maybe related to #554
