### ISSUE TITLE
"Make sure that you are logged into steamcommunity.com in order to be able to use all features of Augmented Steam."

### ISSUE THREAD

**Issue by bringonblink** [tfedor/AugmentedSteam#479]
i get [this](https://i.imgur.com/TDbD5lt.png) error when using augmented steam.

[Here](https://i.imgur.com/fU2v5Bl.png) is the console error.

Any way to make it go away?

**Comment by Revadike** [comment]
Try (re)logging in to http://steamcommunity.com/login

**Comment by MxtOUT** [comment]
There is no error in your console.
Could you [look at your background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page) console?

**Comment by telans** [comment]
> There is no error in your console.
> Could you [look at your background page](https://github.com/tfedor/AugmentedSteam/wiki/Debugging#inspecting-the-background-page) console?

The red banner appears due to having third-party cookies blocked.

![Screenshot_20190906_140243](https://user-images.githubusercontent.com/45819748/64395667-8f30ad00-d04a-11e9-93db-6f039a34e649.png)

Add `https://store.steampowered.com` & `https://steamcommunity.com` to your cookie exceptions with the status `Allow`, and this goes away.

Also just a heads up, the [debugging section for Firefox 69 has changed](https://techdows.com/wp-content/uploads/2019/04/about-debugging-to-replace-Firefox-WebIDE.png), and is no longer similar to the current screenshots. Debugging is now accessed via the `Inspect` button, under `This Firefox`

**Comment by MxtOUT** [comment]
For the next version this warning will be disabled until we found a better solution for handling these cases.
Relevant commit: c05b0168af7523c5f09df3cf4cc2587220f9d73a

**Comment by Revadike** [comment]
This issue seems to be related to https://github.com/tfedor/AugmentedSteam/issues/479 as well

**Comment by MxtOUT** [comment]
This **is** issue #479

**Comment by Revadike** [comment]
Sorry I meant #519

**Comment by MxtOUT** [comment]
Disabled this warning for now in c05b0168af7523c5f09df3cf4cc2587220f9d73a

**Comment by MxtOUT** [comment]
As @Revadike pointed out, this is related to #519, hence I am closing this issue and leave everything as-is (so the warning stays removed)
