### ISSUE TITLE
Remove list of all friends that own a game (seems obsolete)

### ISSUE THREAD

**Issue by tfedor** [tfedor/AugmentedSteam#54]
Remove (or at least hide under option) functionality for showing all friends that own a game - this seems to be obsolete, Steam seems to list all users (albeit not in one list, but split to those who played it recently and those who own the game)

**Comment by KarlCastle** [comment]
PR includes English localization for new text on the Options page. Not sure what needs to be done for other localizations?

**Comment by bottleblue** [comment]
Is the list for playing the game the same as owning the game? If you play a demo or free weekend doesn't that include you in the list as playing the game? I find a list for actually owners of the game to be more useful.

**Comment by RathaWynter** [comment]
I'd like to see the full list be kept, although is it even still in the program? I've not seen this feature working in Enhanced Steam or Augmented Steam in like a year.

I just tested the new 9.3 Augmented Steam enhancement in Chrome 72 and the full list of people who own the game isnt there like it once was. The list Is split into groups like 'currently playing', 'have played in the last two weeks', 'have played previously', 'have in library (with no play time shown because of privacy / 0 hours', and then finally 'have wishlisted' but no full list below that.

**Comment by RathaWynter** [comment]
Theres already an option for this seemingly, its at the bottom of the Community options page: "Show all friends that own"

**Comment by KarlCastle** [comment]
The Steam sections are:
Your own playtime
Friends who have played X in the last 2 weeks
Friends who have played X previously
Friends who have X in their library
Friends who want X

Then the Augmented Steam "All friends who own this".

It's a free weekend for Deep Rock Galactic and I have friends who are playing it, they still show in the wishlist section and not in any of the Steam sections indicating ownership and the counts only reflect ownership. So, playing on a free weekend does *not* include you in the list as playing the game.
