### ISSUE TITLE
[Suggestion] Make alternative Linux icon monochrome to match Win/Mac icons

### ISSUE THREAD

**Issue by ZeusOfTheCrows** [tfedor/AugmentedSteam#561]
I'm happy to make one if needed, or you could use a preexisting one.

**Comment by i-need-to-tell-you-something** [comment]
AFAIU this is in all releases since 1.4.0 and currently live. I _do_ appreciate everyone's effort, but technically this is actually not a monochrome icon.
![](https://i.imgur.com/DWqNCR0.png)
For proper consistency with the other icons it should be entirely white. Some options include:

1. With the current icon - replace white with alpha and replace black with white.
2. With [this](https://www.flaticon.com/free-icon/linux_121147) slightly higher quality icon - replace black with alpha. License permits alterations, but requires an attribution in the credits.

At all reasonable screen resolutions any differences between suggestions 1 and 2 are probably virtually invisible. 

@MxtOUT I'd gladly amateurishly do the edits mentioned in either suggestion (I have a very slight preference for 2 myself) and submit a PR asap when this idea is approved by you or someone else qualified. :wrench:

**Comment by MxtOUT** [comment]
@i-need-to-tell-you-something Yes, 2 seems like a good idea

**Comment by i-need-to-tell-you-something** [comment]
Made a PR. This is how it looks like for me if I edit the image link in css in Firefox developer tools:
![image](https://user-images.githubusercontent.com/9165395/95243637-9ad83f80-0819-11eb-93e7-ded2bc56cdff.png)

There is a completely separate issue for Linux icon here though #893. There is also a PR waiting to fix that one: #772.
