### ISSUE TITLE
Load Market Stats possible bug

### ISSUE THREAD

**Issue by Byemoonmen** [tfedor/AugmentedSteam#611]
It loads up to a certain point and then returns an error. This is the console:
![image](https://user-images.githubusercontent.com/57161818/67821947-8c2bc900-fa9d-11e9-9269-6d9813233138.png)

I'm not sure if that's a bug or maybe a DDoS protection (is this a long shot? I'm kinda clueless about this) steam has

**Comment by Revadike** [comment]
It usually has a different error code for too many connections. Status 500 means something went wrong on Valve's side. Try opening the page yourself (the url ending with start=4000). Maybe it says something useful.

**Comment by Byemoonmen** [comment]
I decided to open up every single one of them, and they all seem to be in HTML (I think), as in, words/code only.

The page 4000 however, shows up like this:

![image](https://user-images.githubusercontent.com/57161818/67823095-88e60c80-faa0-11e9-8eb8-de25085b4604.png)

**Comment by Revadike** [comment]
Does the error happen every time?

**Comment by Byemoonmen** [comment]
Yes, and always at the page 4000

**Comment by Revadike** [comment]
Well, if you're willing to test one more thing. When it is loading these stats, open the console and go to the network tab. There you'll see all the network requests that are being made. Eventually the request for page 4000 will show up too and likely color red (if you have chrome), due to the error. Then, click on it and go to the preview or response tab. I wanna know what you see there.

**Comment by Byemoonmen** [comment]
Same thing: 
![image](https://user-images.githubusercontent.com/57161818/67823684-baf86e00-faa2-11e9-8c8f-f6c7a147a737.png)

**Comment by Revadike** [comment]
And it has the 500 status code?

**Comment by Byemoonmen** [comment]
Yes 
![image](https://user-images.githubusercontent.com/57161818/67823775-26424000-faa3-11e9-8418-2fa451412ba1.png)

**Comment by Revadike** [comment]
Then it seems to me we can just treat error 500 as like nothing happened in this case.

**Comment by Byemoonmen** [comment]
Hopefully I managed to help

**Comment by MxtOUT** [comment]
@Revadike No, this is an HTML instead of a JSON response, so we'd have to adjust the parsing.
But I don't think that this is an error on our side.

@Byemoonmen Could you check one of the other requests?
What properties does the response and values does the response have (like `assets`, `hovers`, `pagesize`, ...)?
You don't need to include your sensitive data from `assets`, `hovers` and `results_html`

**Comment by Revadike** [comment]
huh, how come just one request is in HTML?

**Comment by MxtOUT** [comment]
Probably related to the HTTP 500

**Comment by MxtOUT** [comment]
They should appear under the "Preview" tab that you showed earlier.
If the response is JSON, you should be able to expand the entries, like in the picture.

![image](https://user-images.githubusercontent.com/14999077/69906062-c7cbf280-13bd-11ea-88d7-6700e1a9b141.png)

**Comment by Byemoonmen** [comment]
I just now saw the email that there was a reply here, sorry.

@MxtOUT Found it. During testing, something interesting happened, it's not giving back any errors anymore, now it seems to fully load properly. I'm not sure if there was an update to this plugin or something on Steam's end, but it's gone.

![image](https://user-images.githubusercontent.com/57161818/70592727-84416780-1bb9-11ea-950a-8f7e1c089ffa.png)

You still want to see the assets, hovers, pagesize...? I had a look and the only thing that seems to differ are the sizes, from 33 KB to 160 KB.

**Comment by MxtOUT** [comment]
You had an HTTP 500 status code, so that means that was Steam's fault.
Closing this, thanks for reporting!
