### ISSUE TITLE
Current Player Count Incorrect

### ISSUE THREAD

**Issue by nathanielcwm** [tfedor/AugmentedSteam#71]
The current player count is incorrect on https://store.steampowered.com/app/1025580/Vainglory/ for me. https://steamcharts.com/app/1025580 At the moment shows: ``` 1,256 playing an hour ago,
1,796 24-hour peak,
1,796 all-time peak```
But on the steam page it shows: ```1,040 playing now,
1,040 today's peak,
1,040 all-time peak```

**Comment by MxtOUT** [comment]
The data you are seeing on the page is retrieved from the Enhanced Steam API and not directly from [steamcharts'](https://steamcharts.com/) API endpoint for the following [reason](https://github.com/tfedor/Enhanced_Steam_API_Server/blob/master/README.md):

> Data obtained from external endpoints is sometimes cached to the local MySQL server for later quick retrieval. This was done to reduce the load on external sites against millions of Enhanced Steam API users hitting their endpoints daily, please keep these conventions in place to extend the same courtesies.

**Comment by snakecase** [comment]
@MxtOUT 
Wouldn't it be better to cache such data more frequently per user visit every few hours for example? I guess right now ES polls each game on Steamcharts every few days which seems too redundant as majority of games probably get rarely visited being buried under the fraction of most popular titles therefore it would make more sense to poll games per player visit and cache it for 2-6 hours and then poll again if they get another visit after cache expires.

Because right now it's useless for new and trendig games. Take [this](https://store.steampowered.com/app/548430/Deep_Rock_Galactic/) one for example. On Steam page it shows
![2019-03-01_23-52-00](https://user-images.githubusercontent.com/4579891/53659298-0856de00-3c7d-11e9-9fe1-5589cae8c19d.png) right now so I got confused because the game just landed its anniversary event also got news coverage and should have had at least few thouthands of players but then I checked Steamcharts and it made sense
![2019-03-01_23-54-22](https://user-images.githubusercontent.com/4579891/53659431-5ec41c80-3c7d-11e9-84f6-ed007bd8d0e6.png)

I'm not sure how old ES implemented it but I remember it always showed actual data.

**Comment by RathaWynter** [comment]
Because the readout indicates that there are X players "playing now", we're led to believe that the data is accurate. If we know the data isnt accurate we can then consider it accordingly or will know to check the Steamcharts page directly if we need more recently updated information.

Assuming that player data scraped from Steamcharts is going to be outdated, displaying the Time/Date or how Long Ago the data was updated would be useful until a more permanent solution can be implemented.

(Time/Date would need to be translated into the user's local time unless using 'how long ago')
'592 players on:
Mar 29, 10:50am'

Alternate method:
'592 players
4h 36m ago'

**Comment by snakecase** [comment]
I agree with @RathaWynter though there never was such a problem on original ES.

**Comment by MxtOUT** [comment]
@snakecase I doubt that ES always fetched the newest data for every user visit.
@RathaWynter That sounds like a good solution, but would also require some server-side modifications, which I'm not capable of doing

**Comment by tfedor** [comment]
I've changed the caching time, it should be more up to date now.

**Comment by Revadike** [comment]
@snakecase has a point though. It would be better if you cache on a per app basis. So, lets say that your cache time is 1 hour.
Every time a user requests this data, if the data is older than 1 hour, request the newest data.
This way, steam pages that never or rarely gets visited, don't get their cache refreshed.
Assuming this isn't already the case...

**Comment by Revadike** [comment]
Actually, since [https://steamdb.info/api/GetCurrentPlayers/?appid=440&source=extension_steam_store](SteamDB's GetCurrentPlayer's API] might be used to show DEPOT UPDATE information (https://github.com/tfedor/AugmentedSteam/issues/47), the current player data could be used as well.

**Comment by MxtOUT** [comment]
Just for reference, it won't get used

**Comment by MxtOUT** [comment]
Closing this issue since the original title has nothing to do with the discussed matter, see #669
