### ISSUE TITLE
Wrong store currency

### ISSUE THREAD

**Issue by MxtOUT** [tfedor/AugmentedSteam#858]
See https://github.com/tfedor/AugmentedSteam/issues/656#issuecomment-613410818

**Comment by MxtOUT** [comment]
@deluxghost So you said that `getCurrencyFromDom()` and `getCurrencyFromWallet()` don't return anything, but that's normal on package pages.
The next step is calling the background action `currency`, so could you tell me the course of `SteamStore.currency` on background.js?

**Comment by deluxghost** [comment]
Oh wait, I got it, the USD I mentioned is a cached value before I log in, and that value will cache for 3600s, so the problem is AS doesn't fetch a new currency after every logging in. That explains why my cached currency is related to IP too (which is weird but now we know it was steam detecting my IP)

and about the bundle price, I learned it shows negative price if I owned games of the bundle, so nothing wrong there

so, the only problem here is, **can AS refresh currency cache after logging in and logging out?**
