### ISSUE TITLE
Alternative Linux icon not displayed on Firefox

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [tfedor/AugmentedSteam#893]
The "Show alternative Linux icon" option seems to only work on Chrome, but not on Firefox.

I asked a friend to test this as well and they also observed the icon not working.

Firefox 76.0.1 (64-bit)
Ubuntu 18.04

Might be connected:
I couldn't reproduce it, but once I also saw the Windows icon unloaded/removed from a game that definitely had Win+Mac+Linux support about half a second after most of the website (including the supported platforms icons) without anything else (e.g. tux icon) displayed instead of it. Sounds like it might have been AS (adjustments to page right after loading). When I disabled all addons except for AS and reloaded the page, the problem persisted. Turning off the "Show alternative Linux icon" option and reloading page didn't fix it either. Disabling AS and reloading did fix it. Still, since this happened only once, I can't definitively claim these observations are causal relationships. I might have missed other factors.

**Comment by candela97** [comment]
Can confirm. Looks like on Firefox it's overwritten by: https://github.com/tfedor/AugmentedSteam/blob/5cd57701c855544cc41d16d15f26b0f91da3c959/css/enhancedsteam.css#L221

Those styles were added in https://github.com/jshackles/Enhanced_Steam/commit/a2abd7dd8d563708d85c223d0b2aebc5d7276f2b, but they're not needed anymore since Steam shows platform icons on wishlist items now.

**Comment by i-need-to-tell-you-something** [comment]
Thanks! I hope it gets merged.

**Comment by i-need-to-tell-you-something** [comment]
#772 is now merged and presumably will show up after the next release (current release is v1.4.8).
