### ISSUE TITLE
Option to change account name to display name in any instance, not just in the header.

### ISSUE THREAD

**Issue by Asbu666** [tfedor/AugmentedSteam#930]
I'd like to have the option to change my account name in every place it occurs such as the account details tab, the logout button and the tab itself, not just in the header of the steam page. It'd make streaming a lot easier as I wouldn't have to make sure every time there was no way of my browser being seen when for example logging out in the browser.

**Comment by candela97** [comment]
Steam uses the same class `h2.pageheader` for nearly all page headers, which causes problems when searching and replacing account names: what if part of your account name is also part of the original text? We will also need to limit this feature to a subset of pages, since running this globally is already causing bugs such as the link in Curator page titles dissappearing.

**Comment by MxtOUT** [comment]
> It'd make streaming a lot easier as I wouldn't have to make sure every time there was no way of my browser being seen when for example logging out in the browser.

@Asbu666 I don't quite get what you're trying to say here.
The viewers will see your browser if you log out on stream and this has nothing to do with the account name
