### ISSUE TITLE
Price info not showing on wishlist

### ISSUE THREAD

**Issue by bdcarr** [tfedor/AugmentedSteam#953]
![image](https://user-images.githubusercontent.com/1940488/97658825-6f1b4300-1ac1-11eb-91c7-0742bea163cd.png)

![image](https://user-images.githubusercontent.com/1940488/97658760-43985880-1ac1-11eb-8676-76252371c61e.png)

![image](https://user-images.githubusercontent.com/1940488/97658779-514dde00-1ac1-11eb-96dc-216425e99299.png)

All ad blocking is disabled, I've done 'empty cache and hard reload', no diff.

**Comment by candela97** [comment]
Still having issues? Seems to work fine for me.

**Comment by bdcarr** [comment]
![image](https://user-images.githubusercontent.com/1940488/102945277-6bc89480-4511-11eb-896c-0faf49c26ad4.png)

Yeah, still not showing price history

**Comment by candela97** [comment]
Just to make sure, does price history show on app pages for you? Can you also try scrolling down to the bottom then back up?

I managed to reproduce this on a small wishlist (<5 items). Since Steam caps the number of wishlist rows visible on the page, we observe changes to the wishlist container and add price history to items when they become visible, but if there're very few items, they're always visible and no changes will occur in the wishlist container...

**Comment by bdcarr** [comment]
Hi mate, it's started working again actually. It might've been working at the time of my last comment, because I didn't think to check mouseover (thought it just showed up always).

When I first logged the issue though, it was definitely occurring, because I remember mousing over the entries.

Sorry I can't be of more help.
